name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v6.0.2

      - name: Setup Python.
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install pre-commit.
        run: |
          pip install -U pre-commit

      - name: Set PY env var.
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Restore pre-commit cache.
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit.
        run: |
          pre-commit run --show-diff-on-failure --color=never --all-files --verbose
